# Jekyll configuration
markdown: kramdown
highlighter: rouge
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: Ravinder Nehra
description: Security Enthusiast - Developer
cover: assets/images/blog-cover.png
#logo: assets/images/logo.jpg
#logo_dark: assets/images/logo.jpg
#favicon: assets/images/favicon.png
production_url: 
source_url:
CNAME: #add cname for website to be created

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: rnehra01 # replace by your username
facebook: rnehra01 # replace by your username
mail: hnehra1@gmail.com
github: rnehra01
linkedin: rnehra01

# Disqus
disqus: False
disqus_shortname: "rnehra01-github-io" # replace with your disqus username

# Google Analytics
google_analytics: "UA-102153288-1" # replace with your GA tracking identifier

#algolia
algolia:
  application_id: GVFM3KX3UX
  index_name: rnehra01.github.io
  search_only_api_key: 4f0ffe8c2149d573ab7f386921c55713
  files_to_exclude: [
    index.html,
    about/index.md
  ]
  settings:
    attributesToSnippet: ['*:33']
    highlightPreTag: '<em class="ais-match-highlight">'
    highlightPostTag: '</em>'

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate-v2, jekyll-feed, jekyll-sitemap, jekyll-toc]

feed:
  path: feed.xml

# Pagination Settings
permalink: /:title

pagination:
  enabled: true
  per_page: 5
  permalink: '/:title'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  tags:
    layouts: 
      - 'tag.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: rnehra01
repo: rnehra01.github.io
branch: source
relative_source: ../rnehra01.github.io/
destination: ./_site/
production_url:  https://rnehra01.github.io/
source_url:  https://github.com/rnehra01/rnehra01.github.io/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
