# Site settings
title: Ravinder Nehra
header-img: assets/img/home-bg.jpg
email: hnehra1@gmail.com
description: "My Personal Blog"
baseurl: ""
url: "https://rnehra01.github.io.com"
twitter_profile: https://twitter.com/rnehra01
github_profile: https://github.com/rnehra01
facebook_profile: https://facebook.com/rnehra01
linkedin_profile: https://www.linkedin.com/in/ravinder-nehra-bba51b125/
google_profile: https://plus.google.com/100981026965511230044
email:  hnehra1@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
paginate_path: "/blog/:num"
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
